### PR TITLE
Compile using protobuf

### PR DESCRIPTION
**Pull request by mmmries**
In the spirit of making small/fast changes I'm adding an extremely simple function spec that expects to be able to compile a message, then it requires that message and checks to see that a class was defined.

I'm using the `protobuf` gem to bootstrap this process. Once we get our compilation process complete enough to compile the plugin definitions we'll remove that dependency and we'll self-host the decoding of the message we get from `protoc`, but for now this gets us up and running with an end-to-end test.

### CODE REVIEW

**Comment by mmmries** [comment]
To clarify the plan here:
- #3 and #4 were explorations to decide what kind of code we wanted to generate, they are not intended to be merged, just to discuss the tradeoffs of how much we want to generate and how much we want to use library code at runtime
- this PR is intended to be merged

From here I would start adding functional specs that compile a message and then interact with the generated class to verify the behavior we expect from generated classes (ie. initializing with a has of attributes, checking duck types in setters, but deferring coercion and bounds checking until the encoding step).

**Comment by mmmries** [comment]
Any issues with this? I'll just merge this and move forward unless there are objections.

**Comment by localshred** [comment]
Obviously missed the in-person discussions, but I'm assuming you guys didn't want to just work on splitting my gem apart and working on the message API? Also you weren't interested in google's new ruby impl or even beefcake? Seems like a problem that's been solved by a lot of different orgs.

**Comment by localshred** [comment]
To be clear, I obviously don't have any objections for you guys moving forward, just wondering where the thought process was at.

**Comment by mmmries** [comment]
@localshred I would love to pick your brain on the topic since you have dived into these depths before. Here are the top things we are aiming for with this implementation:
- Pury-ruby implementation
- De-couple the serialization logic from RPC logic
- Generate complete classes during protobuf compilation rather than defining methods at runtime

We could get the first 2 by working on splitting `protobuf` apart, but we want to generate more verbose message classes and have less dependency on the library at runtime. [Google's recent gem](https://rubygems.org/gems/google-protobuf) is just a wrapper around the C library so it won't work on jRuby.

I haven't dug too much into `beefcake`, but it looks like it follows a similar pattern to protobuf where it represents the protobuf schema in ruby, and the implementation of getters/setters/validations/coercions/encoding/decoding all happen at runtime. So for the most part this is just an experiment to see if we like the idea of generating more the implementation at compile time and less at runtime.

**Pull request closed without merging**
